language: go
go:
- '1.10'
sudo: false
before_script:
- 'mkdir -p $GOPATH/bin && wget -q https://github.com/barnybug/go-cast/releases/download/deps/upx -O $GOPATH/bin/upx && chmod +x $GOPATH/bin/upx'
script:
- make test
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | VERSION=0.34.2 bash
  on:
    tags: true
